services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - solar-backend
    restart: unless-stopped
    networks:
      - my_network

  solar-backend:
    build: ./solar-backend-fastapi
    container_name: solar-backend
    # volumes:
    #   - shared_data:/usr/src/app/shared_data
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge